import '@radix-ui/themes/styles.css';
import './globals.css';
import type { Metadata } from 'next';
import NavBar from '@/components/layout/NavBar';
import { Theme } from '@radix-ui/themes';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Theme>
					<NavBar />
					<main className='p-5'>{children}</main>
				</Theme>
			</body>
		</html>
	);
}
