import '@radix-ui/themes/styles.css';
import './globals.scss';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import NavBar from '@/components/layout/NavBar';
import { Container, Theme } from '@radix-ui/themes';
import AuthProvider from '@/auth/Provider';
import QueryClientProvider from '@/config/QueryClientProvider';
import Footer from '@/components/layout/Footer';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.variable}>
				<QueryClientProvider>
					<AuthProvider>
						<Theme
							accentColor='violet'
							className={`${inter.variable} min-h-screen flex flex-col`}
						>
							<NavBar />
							<main className='p-5 flex-1'>
								<Container>{children}</Container>
							</main>
							<Footer />
						</Theme>
					</AuthProvider>
				</QueryClientProvider>
			</body>
		</html>
	);
}
